Repository xnvme/xnvme, pull requests merged in 2023-11, with the labels that each got.

#374 bump libvfn to v3.0.0-rc2
  toolbox/pkgs/alpine-latest.sh
  toolbox/pkgs/archlinux-latest.sh
  toolbox/pkgs/centos-stream9.sh
  toolbox/pkgs/debian-bookworm.sh
  toolbox/pkgs/debian-bullseye.sh
  toolbox/pkgs/debian-trixie.sh
  toolbox/pkgs/emitter/templates/src-libvfn.sh.jinja
  toolbox/pkgs/fedora-36.sh
  toolbox/pkgs/fedora-37.sh
  toolbox/pkgs/fedora-38.sh
  toolbox/pkgs/gentoo-latest.sh
  toolbox/pkgs/opensuse-tumbleweed-latest.sh
  toolbox/pkgs/oraclelinux-9.sh
  toolbox/pkgs/rockylinux-9.2.sh
  toolbox/pkgs/ubuntu-focal.sh
  toolbox/pkgs/ubuntu-jammy.sh
  toolbox/pkgs/ubuntu-lunar.sh
Labels: bug

#384 docs(release-checklist): add description on Python + Rust publication
  docs/contributing/release-checklist.rst
Labels: documentation

#383 fix(rust): use header found via system_deps()
  rust/xnvme-sys/build.rs
Labels: bug

#395 Remove metadata buffer checks
  lib/xnvme_be_linux_async_ucmd.c
Labels: bug, enhancement

#394 fix(nvm): change sdlba to slba for write_zeroes
  include/libxnvme_nvm.h
  lib/xnvme_nvm.c
Labels: documentation, enhancement

#397 docs(release-checklist): add description of Rust publication
  docs/contributing/release-checklist.rst
Labels: documentation
