Repository xnvme/xnvme, pull requests merged in 2023-04, with the labels that each got.

#276 ci/build_and_test: kill qemu and remove guest-directory
  .github/workflows/verify.yml
Labels: bug, enhancement, pr-ready-for-test

#278 docs/tutorial: adjust to build-improvements
  docs/tutorial/dynamic_loading/010_run_c_example.cmd
  docs/tutorial/dynamic_loading/enumerate_example.py
Labels: bug, documentation, pr-ready-for-test

#279 rpmbuild: fix directory conflicts error
  xnvme.spec.in
Labels: bug, pr-ready-for-test

#280 toolbox/cijoe-pkg-xnvme: pin cijoe version
  toolbox/cijoe-pkg-xnvme/setup.py
Labels: enhancement, pr-ready-for-test
