Repository xnvme/xnvme, pull requests merged in 2024-10, with the labels that each got.

#543 fix(cijoe/bench): enable poll queues before running bench
  cijoe/workflows/bench.yaml
Labels: bench

#542 vfio phy mapping
  lib/xnvme_be_vfio_mem.c
Labels: bug, enhancement, bench

#544 refactor(api/znd)!: replace report-MACROs with getters
  include/libxnvme_znd.h
  lib/libxnvme.map
  lib/xnvme_znd.c
  tests/znd_explicit_open.c
Labels: enhancement
