Repository xnvme/xnvme, pull requests merged in 2024-11, with the labels that each got.

#552 fix(lib): format characters
  lib/xnvme_be_windows.c
  lib/xnvme_be_windows_async_iocp.c
  lib/xnvme_be_windows_async_ioring.c
  lib/xnvme_pi.c
Labels: bug

#551 refactor(libconf)!: replace extern xnvme_libconf with struct and getter
  include/libxnvme_libconf.h
  lib/libxnvme.map
  lib/meson.build
  lib/xnvme_libconf.c
  lib/xnvme_libconf_entries.c
  python/bindings/bin/xpy_libconf
  python/bindings/xnvme/ctypes_bindings/tests/test_loader.py
  python/tests/test_basics.py
  toolbox/xnvme_libconf.py
  tools/xnvme.c
Labels: enhancement

#549 fix(cijoe): add `./` as prefix to local file for `pipx inject`
  cijoe/scripts/xnvme_bindings_py_install_tgz.py
Labels: bug, bench
